/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of InvalidReqType
 */
interface InvalidReqType {
  InvalidReqTypeError?: InvalidReqTypeError;
}

export class InvalidReqTypeError extends ApiError<InvalidReqType> {}
