/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { unknown } from '../schema';
import { BaseController } from './baseController';

export class HealthController extends BaseController {
  /**
   * @return Response from the API call
   */
  async healthCheck(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/health-check');
    return req.callAsJson(unknown(), requestOptions);
  }
}
