/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  BillToContactPostOrder,
  billToContactPostOrderSchema,
} from './billToContactPostOrder';

/**
 * The information of the new account to be created with the order. Note
 * that this actually specifies the invoice owner account of the
 * subscriptions included in this order. To create the new account,
 * either a **creditCard** structure or the
 * **hpmCreditCardPaymentMethodId** field (but not both) should be
 * provided. The one provided becomes the default payment method for this
 * account. If the credit card information is declined or can't be
 * verified, then the account is not created.
 */
export interface Account {
  accountNumber?: string;
  /** List of additional email addresses to receive emailed invoices. Values should be a comma-separated list of email addresses. */
  additionalEmailAddresses?: string;
  /** Name of the account's customer service representative, if applicable. */
  customerServiceRepName?: string;
  /** The number of the purchase order associated with this account. Purchase order information generally comes from customers. */
  purchaseOrderNumber?: string;
  /** The name of the sales representative associated with this account, if applicable. */
  salesRep?: string;
  /**
   * The ID of the billing document sequence set to assign to the customer account.
   * The billing documents to generate for this account will adopt the prefix and starting document number configured in the sequence set.
   */
  sequenceSetId?: string;
  /**
   * Indicates if associated invoices can be edited.
   * Values are:
   * * `true`
   * * `false` (default)
   */
  allowInvoiceEdit?: boolean;
  name?: string;
  /** 3 uppercase character currency code */
  currency?: string;
  /** Day of the month that the account prefers billing periods to begin on. If set to 0, the bill cycle day will be set as "AutoSet". */
  billCycleDay?: number;
  /**
   * Specifies whether to turn on the invoice delivery method 'Print' for the new account.
   * Values are:
   * * `true`. Turn on the invoice delivery method 'Print' for the new account.
   * * `false` (default). Turn off the invoice delivery method 'Print' for the new account.
   */
  invoiceDeliveryPrefsPrint?: boolean;
  /**
   * Specifies whether to turn on the invoice delivery method 'Email' for the new account.
   * Values are:
   * * `true` (default). Turn on the invoice delivery method 'Email' for the new account.
   * * `false`. Turn off the invoice delivery method 'Email' for the new account.
   */
  invoiceDeliveryPrefsEmail?: boolean;
  /** Specifies whether future payments are to be automatically billed when they are due. Possible values are `true`, `false`. */
  autoPay?: boolean;
  paymentTerm?: string;
  /** aaa. */
  communicationProfileId?: string;
  /** Organizes your customer accounts into groups to optimize your billing and payment operations. */
  batch?: string;
  /** Invoice template ID, configured in Billing Settings. */
  invoiceTemplateId?: string;
  /** The unique ID of the debit memo template, configured in Billing Settings. */
  debitMemoTemplateId?: string;
  /** The unique ID of the credit memo template, configured in Billing Settings. */
  creditMemoTemplateId?: string;
  billToContact?: BillToContactPostOrder;
  soldToContact?: BillToContactPostOrder;
}

export const accountSchema: Schema<Account> = object({
  accountNumber: ['accountNumber', optional(string())],
  additionalEmailAddresses: ['additionalEmailAddresses', optional(string())],
  customerServiceRepName: ['customerServiceRepName', optional(string())],
  purchaseOrderNumber: ['purchaseOrderNumber', optional(string())],
  salesRep: ['salesRep', optional(string())],
  sequenceSetId: ['sequenceSetId', optional(string())],
  allowInvoiceEdit: ['allowInvoiceEdit', optional(boolean())],
  name: ['name', optional(string())],
  currency: ['currency', optional(string())],
  billCycleDay: ['billCycleDay', optional(number())],
  invoiceDeliveryPrefsPrint: ['invoiceDeliveryPrefsPrint', optional(boolean())],
  invoiceDeliveryPrefsEmail: ['invoiceDeliveryPrefsEmail', optional(boolean())],
  autoPay: ['autoPay', optional(boolean())],
  paymentTerm: ['paymentTerm', optional(string())],
  communicationProfileId: ['communicationProfileId', optional(string())],
  batch: ['batch', optional(string())],
  invoiceTemplateId: ['invoiceTemplateId', optional(string())],
  debitMemoTemplateId: ['debitMemoTemplateId', optional(string())],
  creditMemoTemplateId: ['creditMemoTemplateId', optional(string())],
  billToContact: [
    'billToContact',
    optional(lazy(() => billToContactPostOrderSchema)),
  ],
  soldToContact: [
    'soldToContact',
    optional(lazy(() => billToContactPostOrderSchema)),
  ],
});
