/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  UpdateOrAddProductChargeOverride,
  updateOrAddProductChargeOverrideSchema,
} from './updateOrAddProductChargeOverride';

/**
 * Information about an order action of type `addProduct`.
 * If you want to create a pending order through the "Add product" order action, and if the charge's trigger condition is `Specific Date`, you must set a charge number in the `chargeNumber` field for the "Add product" order action.
 */
export interface AddProduct {
  /** Internal identifier of the product rate plan that the rate plan is based on. */
  productRatePlanId?: string;
  updateOrAddProductChargeOverrides?: UpdateOrAddProductChargeOverride[];
}

export const addProductSchema: Schema<AddProduct> = object({
  productRatePlanId: ['productRatePlanId', optional(string())],
  updateOrAddProductChargeOverrides: [
    'updateOrAddProductChargeOverrides',
    optional(array(lazy(() => updateOrAddProductChargeOverrideSchema))),
  ],
});
