/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Contact details associated with an account. */
export interface BillToContactPostOrder {
  /** First line of the contact's address. This is often a street address or a business name. */
  address1?: string;
  /** Second line of the contact's address. */
  address2?: string;
  /** City of the contact's address. */
  city?: string;
  /** Country; must be a valid country name or abbreviation. If using Zuora Tax, you must specify a country in the bill-to contact to calculate tax. */
  country?: string;
  /** County of the contact's address. */
  county?: string;
  /** First name of the contact. */
  firstName?: string;
  /** Last name of the contact. */
  lastName?: string;
  /** Mobile phone number of the contact. */
  mobilePhone?: string;
  /** Personal email address of the contact. */
  personalEmail?: string;
  /** ZIP code or other postal code of the contact's address. */
  postalCode?: string;
  /** State or province of the contact's address. */
  state?: string;
  /** Business email address of the contact. */
  workEmail?: string;
  /** Business phone number of the contact. */
  workPhone?: string;
}

export const billToContactPostOrderSchema: Schema<BillToContactPostOrder> = object(
  {
    address1: ['address1', optional(string())],
    address2: ['address2', optional(string())],
    city: ['city', optional(string())],
    country: ['country', optional(string())],
    county: ['county', optional(string())],
    firstName: ['firstName', optional(string())],
    lastName: ['lastName', optional(string())],
    mobilePhone: ['mobilePhone', optional(string())],
    personalEmail: ['personalEmail', optional(string())],
    postalCode: ['postalCode', optional(string())],
    state: ['state', optional(string())],
    workEmail: ['workEmail', optional(string())],
    workPhone: ['workPhone', optional(string())],
  }
);
