/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface BillingOptions {
  documentDate?: string;
  /** For REDEMPTION, it is end of term date */
  targetDate?: string;
}

export const billingOptionsSchema: Schema<BillingOptions> = object({
  documentDate: ['documentDate', optional(string())],
  targetDate: ['targetDate', optional(string())],
});
