/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import {
  SubscriptionSourceEnum,
  subscriptionSourceEnumSchema,
} from './subscriptionSourceEnum';

export interface CancelReqType {
  /** Subscription id */
  subscriptionId: string;
  /** Internal or external */
  subscriptionSource: SubscriptionSourceEnum;
  /** Reason for subscription cancel */
  cancelReason: string;
  /** cancellation date */
  cancelDate: string;
}

export const cancelReqTypeSchema: Schema<CancelReqType> = object({
  subscriptionId: ['subscriptionId', string()],
  subscriptionSource: ['subscriptionSource', subscriptionSourceEnumSchema],
  cancelReason: ['cancelReason', string()],
  cancelDate: ['cancelDate', string()],
});
