/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CancelResType {
  /** Response Message */
  message: string;
}

export const cancelResTypeSchema: Schema<CancelResType> = object({
  message: ['message', string()],
});
