/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CodeEnum
 */
export enum CodeEnum {
  E01 = 'E01',
  E40 = 'E40',
  E41 = 'E41',
}

/**
 * Schema for CodeEnum
 */
export const codeEnumSchema: Schema<CodeEnum> = stringEnum(CodeEnum);
