/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CustomerFacingCustomFields {
  customerFacingC?: string;
}

export const customerFacingCustomFieldsSchema: Schema<CustomerFacingCustomFields> = object(
  { customerFacingC: ['customerFacing__c', optional(string())] }
);
