/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for EndDateConditionEnum
 */
export enum EndDateConditionEnum {
  SubscriptionEnd = 'Subscription_End',
  FixedPeriod = 'Fixed_Period',
  SpecificEndDate = 'Specific_End_Date',
}

/**
 * Schema for EndDateConditionEnum
 */
export const endDateConditionEnumSchema: Schema<EndDateConditionEnum> = stringEnum(
  EndDateConditionEnum
);
