/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface InvalidReqTypeError {
  /** Error codes */
  code?: string;
  /** Error message. */
  message?: string;
}

export const invalidReqTypeErrorSchema: Schema<InvalidReqTypeError> = object({
  code: ['code', optional(string())],
  message: ['message', optional(string())],
});
