/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface OrderError {
  /** Error codes. */
  code?: string;
  /** Error message. */
  message?: string;
}

export const orderErrorSchema: Schema<OrderError> = object({
  code: ['code', optional(string())],
  message: ['message', optional(string())],
});
