/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Account, accountSchema } from './account';
import { CustomField, customFieldSchema } from './customField';
import {
  OrderRequestProcessingOptions,
  orderRequestProcessingOptionsSchema,
} from './orderRequestProcessingOptions';
import {
  OrderRequestTypeProduct,
  orderRequestTypeProductSchema,
} from './orderRequestTypeProduct';
import {
  OrderRequestTypeSubscription,
  orderRequestTypeSubscriptionSchema,
} from './orderRequestTypeSubscription';

export interface OrderRequestType {
  /** Hybris/PMC/OASIS Order Number. */
  orderNumber?: string;
  /** The date when the order is signed. All the order actions under this order will use this order date as the contract effective date if the contract effective date field is skipped or its value is left as null. */
  orderDate?: string;
  /** A description of the order. */
  description?: string;
  /** Subscription Model Name. */
  subscriptionModelName?: string;
  /** store identifier */
  storeCode?: string;
  /** Use for swapTitle.If swaptitle than value will be true. */
  swapTitle?: boolean;
  /** send email to the user */
  sendEmail?: boolean;
  account?: Account;
  /** new account details required to create subscription. This block is mandate for new customer */
  orderRequestTypeSubscriptions?: OrderRequestTypeSubscription[];
  /** Invoice or Payment. */
  orderRequestProcessingOptions?: OrderRequestProcessingOptions;
  orderRequestTypeProducts?: OrderRequestTypeProduct[];
  /** Information about the payment related fields. */
  customFields?: CustomField[];
  paymentCapture?: unknown;
}

export const orderRequestTypeSchema: Schema<OrderRequestType> = object({
  orderNumber: ['orderNumber', optional(string())],
  orderDate: ['orderDate', optional(string())],
  description: ['description', optional(string())],
  subscriptionModelName: ['subscriptionModelName', optional(string())],
  storeCode: ['storeCode', optional(string())],
  swapTitle: ['swapTitle', optional(boolean())],
  sendEmail: ['sendEmail', optional(boolean())],
  account: ['account', optional(lazy(() => accountSchema))],
  orderRequestTypeSubscriptions: [
    'orderRequestTypeSubscriptions',
    optional(array(lazy(() => orderRequestTypeSubscriptionSchema))),
  ],
  orderRequestProcessingOptions: [
    'orderRequestProcessingOptions',
    optional(lazy(() => orderRequestProcessingOptionsSchema)),
  ],
  orderRequestTypeProducts: [
    'orderRequestTypeProducts',
    optional(array(lazy(() => orderRequestTypeProductSchema))),
  ],
  customFields: [
    'customFields',
    optional(array(lazy(() => customFieldSchema))),
  ],
  paymentCapture: ['paymentCapture', optional(unknown())],
});
