/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { CodeEnum, codeEnumSchema } from './codeEnum';

export interface OrderRespError {
  /** Error codes. */
  code?: CodeEnum;
  /** Error message. */
  message?: string;
}

export const orderRespErrorSchema: Schema<OrderRespError> = object({
  code: ['code', optional(codeEnumSchema)],
  message: ['message', optional(string())],
});
