/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface OrderRespType {
  /** message description once subscription creation is sucess. */
  message?: string;
  /** order number. */
  orderNumber?: string;
  /** subscription id. */
  subscriptionNumber?: string;
}

export const orderRespTypeSchema: Schema<OrderRespType> = object({
  message: ['message', optional(string())],
  orderNumber: ['orderNumber', optional(string())],
  subscriptionNumber: ['subscriptionNumber', optional(string())],
});
