/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface OrderRequestTypeProduct {
  /** product isbn value */
  isbn?: string;
  /** product ppid value */
  ppid?: string;
  /** Duration of the entitlement in days for this product */
  duration?: number;
  /** Cost of tax on the product */
  tax?: number;
  /** Cost of the product */
  price?: number;
}

export const orderRequestTypeProductSchema: Schema<OrderRequestTypeProduct> = object(
  {
    isbn: ['isbn', optional(string())],
    ppid: ['ppid', optional(string())],
    duration: ['duration', optional(number())],
    tax: ['tax', optional(number())],
    price: ['price', optional(number())],
  }
);
