/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema';
import { BillingOptions, billingOptionsSchema } from './billingOptions';

/** Invoice or Payment. */
export interface OrderRequestProcessingOptions {
  /** Indicates if the current request needs to generate an invoice. The invoice will be generated against all subscriptions included in this order. For REDEMPTION, default it to true. */
  runBilling?: boolean;
  billingOptions?: BillingOptions;
  /** Indicates if the current request needs to collect payments. This value can not be 'true' when 'runBilling' flag is 'false'. */
  collectPayment?: boolean;
}

export const orderRequestProcessingOptionsSchema: Schema<OrderRequestProcessingOptions> = object(
  {
    runBilling: ['runBilling', optional(boolean())],
    billingOptions: [
      'billingOptions',
      optional(lazy(() => billingOptionsSchema)),
    ],
    collectPayment: ['collectPayment', optional(boolean())],
  }
);
