/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderTypeEnum
 */
export enum OrderTypeEnum {
  UPGRADE = 'UPGRADE',
  DOWNGRADE = 'DOWNGRADE',
  RENEWON = 'RENEWON',
  RENEWOFF = 'RENEWOFF',
  MIBUPGRADE = 'MIBUPGRADE',
  MIBRENEWON = 'MIBRENEWON',
  MIBRENEWOFF = 'MIBRENEWOFF',
}

/**
 * Schema for OrderTypeEnum
 */
export const orderTypeEnumSchema: Schema<OrderTypeEnum> = stringEnum(
  OrderTypeEnum
);
