/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PeriodTypeEnum
 */
export enum PeriodTypeEnum {
  Month = 'Month',
  Year = 'Year',
  Day = 'Day',
  Week = 'Week',
}

/**
 * Schema for PeriodTypeEnum
 */
export const periodTypeEnumSchema: Schema<PeriodTypeEnum> = stringEnum(
  PeriodTypeEnum
);
