/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Product {
  /** product isbn number */
  isbn?: string;
  /** product ppid number */
  ppid?: string;
  /** Duration of the entitlement in days for this product */
  duration?: number;
  /** end date for the entitlement. in yyyy-MM-dd'T'HH:mm:ss.SSSZ format. */
  endDate?: string;
  /** Cost of tax on the product */
  tax?: number;
  /** Cost of the product */
  price?: number;
}

export const productSchema: Schema<Product> = object({
  isbn: ['isbn', optional(string())],
  ppid: ['ppid', optional(string())],
  duration: ['duration', optional(number())],
  endDate: ['endDate', optional(string())],
  tax: ['tax', optional(number())],
  price: ['price', optional(number())],
});
