/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import {
  EndDateConditionEnum,
  endDateConditionEnumSchema,
} from './endDateConditionEnum';
import {
  UpToPeriodsTypeEnum,
  upToPeriodsTypeEnumSchema,
} from './upToPeriodsTypeEnum';

export interface RatePlanEndDate {
  /** enum values are "Subscription_End" "Fixed_Period" "Specific_End_Date" */
  endDateCondition?: EndDateConditionEnum;
  specificEndDate?: string;
  /** Duration of the charge in billing periods, days, weeks, months, or years, depending on the value of the upToPeriodsType field. Only applicable if the value of the endDateCondition field is Fixed_Period. */
  upToPeriods?: number;
  /** Unit of time that the charge duration is measured in. Only applicable if the value of the endDateCondition field is Fixed_Period. */
  upToPeriodsType?: UpToPeriodsTypeEnum;
}

export const ratePlanEndDateSchema: Schema<RatePlanEndDate> = object({
  endDateCondition: ['endDateCondition', optional(endDateConditionEnumSchema)],
  specificEndDate: ['specificEndDate', optional(string())],
  upToPeriods: ['upToPeriods', optional(number())],
  upToPeriodsType: ['upToPeriodsType', optional(upToPeriodsTypeEnumSchema)],
});
