/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Discount, discountSchema } from './discount';
import { RecurringFlatFee, recurringFlatFeeSchema } from './recurringFlatFee';

export interface RatePlanPricing {
  discount?: Discount;
  recurringFlatFee?: RecurringFlatFee;
}

export const ratePlanPricingSchema: Schema<RatePlanPricing> = object({
  discount: ['discount', optional(lazy(() => discountSchema))],
  recurringFlatFee: [
    'recurringFlatFee',
    optional(lazy(() => recurringFlatFeeSchema)),
  ],
});
