/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';
import { PeriodTypeEnum, periodTypeEnumSchema } from './periodTypeEnum';

export interface RenewalTerm {
  /** Duration of the renewal term in months, years, days, or weeks, depending on the value of the `periodType` field. */
  period?: number;
  /** Unit of time that the renewal term is measured in. */
  periodType?: PeriodTypeEnum;
}

export const renewalTermSchema: Schema<RenewalTerm> = object({
  period: ['period', optional(number())],
  periodType: ['periodType', optional(periodTypeEnumSchema)],
});
