/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RenewalSettingEnum
 */
export enum RenewalSettingEnum {
  RENEWWITHSPECIFICTERM = 'RENEW_WITH_SPECIFIC_TERM',
  RENEWTOEVERGREEN = 'RENEW_TO_EVERGREEN',
}

/**
 * Schema for RenewalSettingEnum
 */
export const renewalSettingEnumSchema: Schema<RenewalSettingEnum> = stringEnum(
  RenewalSettingEnum
);
