/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  CustomerFacingCustomFields,
  customerFacingCustomFieldsSchema,
} from './customerFacingCustomFields';
import { RatePlanEndDate, ratePlanEndDateSchema } from './ratePlanEndDate';
import { RatePlanPricing, ratePlanPricingSchema } from './ratePlanPricing';

export interface SubscribeToRatePlansChargeOverride {
  /** This is unique rate plan charge id respective to rate plan id. It signifies the subscription type,entitlementLevel,maxEntitlements,numEntitlements etc. */
  productRatePlanChargeId?: string;
  customerFacingCustomFields?: CustomerFacingCustomFields;
  ratePlanPricing?: RatePlanPricing;
  ratePlanEndDate?: RatePlanEndDate;
}

export const subscribeToRatePlansChargeOverrideSchema: Schema<SubscribeToRatePlansChargeOverride> = object(
  {
    productRatePlanChargeId: ['productRatePlanChargeId', optional(string())],
    customerFacingCustomFields: [
      'customerFacingCustomFields',
      optional(lazy(() => customerFacingCustomFieldsSchema)),
    ],
    ratePlanPricing: [
      'ratePlanPricing',
      optional(lazy(() => ratePlanPricingSchema)),
    ],
    ratePlanEndDate: [
      'ratePlanEndDate',
      optional(lazy(() => ratePlanEndDateSchema)),
    ],
  }
);
