/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TermTypeEnum
 */
export enum TermTypeEnum {
  TERMED = 'TERMED',
  EVERGREEN = 'EVERGREEN',
}

/**
 * Schema for TermTypeEnum
 */
export const termTypeEnumSchema: Schema<TermTypeEnum> = stringEnum(
  TermTypeEnum
);
