/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** change the terms and conditions of a subscription . */
export interface TermsAndConditions {
  /** autorenew flag */
  autorenew?: boolean;
}

export const termsAndConditionsSchema: Schema<TermsAndConditions> = object({
  autorenew: ['autorenew', optional(boolean())],
});
