/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface TriggerDate {
  name?: string;
  /** Date in YYYY-MM-DD format. */
  triggerDate?: string;
}

export const triggerDateSchema: Schema<TriggerDate> = object({
  name: ['name', optional(string())],
  triggerDate: ['triggerDate', optional(string())],
});
