/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  AddProductEndDate,
  addProductEndDateSchema,
} from './addProductEndDate';
import {
  CustomerFacingCustomFields,
  customerFacingCustomFieldsSchema,
} from './customerFacingCustomFields';
import { OverridesPricing, overridesPricingSchema } from './overridesPricing';

export interface UpdateOrAddProductChargeOverride {
  /** This is unique rate plan charge id respective to rate plan id. It signifies the subscription type,entitlementLevel,maxEntitlements,numEntitlements etc. */
  productRatePlanChargeId?: string;
  customerFacingCustomFields?: CustomerFacingCustomFields;
  overridesPricing?: OverridesPricing;
  addProductEndDate?: AddProductEndDate;
}

export const updateOrAddProductChargeOverrideSchema: Schema<UpdateOrAddProductChargeOverride> = object(
  {
    productRatePlanChargeId: ['productRatePlanChargeId', optional(string())],
    customerFacingCustomFields: [
      'customerFacingCustomFields',
      optional(lazy(() => customerFacingCustomFieldsSchema)),
    ],
    overridesPricing: [
      'overridesPricing',
      optional(lazy(() => overridesPricingSchema)),
    ],
    addProductEndDate: [
      'addProductEndDate',
      optional(lazy(() => addProductEndDateSchema)),
    ],
  }
);
