/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

/** Invoice or Payment. */
export interface UpdateSubscriptionProcessingOptions {
  /** Indicates if the current request needs to generate an invoice. The invoice will be generated against all subscriptions included in this order. */
  runBilling?: boolean;
  /** Indicates if the current request needs to collect payments. This value can not be 'true' when 'runBilling' flag is 'false'. */
  collectPayment?: boolean;
}

export const updateSubscriptionProcessingOptionsSchema: Schema<UpdateSubscriptionProcessingOptions> = object(
  {
    runBilling: ['runBilling', optional(boolean())],
    collectPayment: ['collectPayment', optional(boolean())],
  }
);
