/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { AddProduct, addProductSchema } from './addProduct';
import { RemoveProduct, removeProductSchema } from './removeProduct';
import {
  TermsAndConditions,
  termsAndConditionsSchema,
} from './termsAndConditions';
import { TriggerDate, triggerDateSchema } from './triggerDate';

export interface UpdateOrderOrderAction {
  triggerDates?: TriggerDate[];
  /**
   * Information about an order action of type `addProduct`.
   * If you want to create a pending order through the "Add product" order action, and if the charge's trigger condition is `Specific Date`, you must set a charge number in the `chargeNumber` field for the "Add product" order action.
   */
  addProduct?: AddProduct;
  /** Remove product details from the subscription plan */
  removeProduct?: RemoveProduct;
  /** change the terms and conditions of a subscription . */
  termsAndConditions?: TermsAndConditions;
}

export const updateOrderOrderActionSchema: Schema<UpdateOrderOrderAction> = object(
  {
    triggerDates: [
      'triggerDates',
      optional(array(lazy(() => triggerDateSchema))),
    ],
    addProduct: ['addProduct', optional(lazy(() => addProductSchema))],
    removeProduct: ['removeProduct', optional(lazy(() => removeProductSchema))],
    termsAndConditions: [
      'termsAndConditions',
      optional(lazy(() => termsAndConditionsSchema)),
    ],
  }
);
