/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  UpdateOrderOrderAction,
  updateOrderOrderActionSchema,
} from './updateOrderOrderAction';

export interface UpdateSubscriptionSubscription {
  /** Subscription number or ID. Subscription status must be active for the same. */
  subscriptionNumber: string;
  /** The actions to be applied to the subscription. Order actions will be stored with the sequence when it was provided in the request. */
  orderActions?: UpdateOrderOrderAction[];
}

export const updateSubscriptionSubscriptionSchema: Schema<UpdateSubscriptionSubscription> = object(
  {
    subscriptionNumber: ['subscriptionNumber', string()],
    orderActions: [
      'orderActions',
      optional(array(lazy(() => updateOrderOrderActionSchema))),
    ],
  }
);
