/**
 * pplus-subscription-papiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Account, accountSchema } from './account';
import { CustomField, customFieldSchema } from './customField';
import { OrderTypeEnum, orderTypeEnumSchema } from './orderTypeEnum';
import { Product, productSchema } from './product';
import {
  UpdateSubscriptionProcessingOptions,
  updateSubscriptionProcessingOptionsSchema,
} from './updateSubscriptionProcessingOptions';
import {
  UpdateSubscriptionSubscription,
  updateSubscriptionSubscriptionSchema,
} from './updateSubscriptionSubscription';

export interface UpdateSubscription {
  /** Order Type . */
  orderType: OrderTypeEnum;
  /** Hybris Order Number. */
  orderNumber?: string;
  /** The date when the order is signed. All the order actions under this order will use this order date as the contract effective date if the contract effective date field is skipped or its value is left as null. */
  orderDate?: string;
  /** A description of the order. */
  description?: string;
  /** The account number that this order will be created under. It can be either the accountNumber or the account info provided. */
  existingAccountNumber?: string;
  account?: Account;
  /** Each item includes a set of order actions, which will be applied to the same base subscription. */
  updateSubscriptionSubscriptions?: UpdateSubscriptionSubscription[];
  /** Invoice or Payment. */
  updateSubscriptionProcessingOptions?: UpdateSubscriptionProcessingOptions;
  updateSubscriptionProducts?: Product[];
  /** Information about the payment related fields. */
  customFields?: CustomField[];
  paymentCapture?: unknown;
}

export const updateSubscriptionSchema: Schema<UpdateSubscription> = object({
  orderType: ['orderType', orderTypeEnumSchema],
  orderNumber: ['orderNumber', optional(string())],
  orderDate: ['orderDate', optional(string())],
  description: ['description', optional(string())],
  existingAccountNumber: ['existingAccountNumber', optional(string())],
  account: ['account', optional(lazy(() => accountSchema))],
  updateSubscriptionSubscriptions: [
    'updateSubscriptionSubscriptions',
    optional(array(lazy(() => updateSubscriptionSubscriptionSchema))),
  ],
  updateSubscriptionProcessingOptions: [
    'updateSubscriptionProcessingOptions',
    optional(lazy(() => updateSubscriptionProcessingOptionsSchema)),
  ],
  updateSubscriptionProducts: [
    'updateSubscriptionProducts',
    optional(array(lazy(() => productSchema))),
  ],
  customFields: [
    'customFields',
    optional(array(lazy(() => customFieldSchema))),
  ],
  paymentCapture: ['paymentCapture', optional(unknown())],
});
