/**
 * Pearson Subscriptions APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UpToPeriodsTypeEnum
 */
export enum UpToPeriodsTypeEnum {
  BillingPeriods = 'Billing_Periods',
  Days = 'Days',
  Weeks = 'Weeks',
  Months = 'Months',
  Years = 'Years',
}

/**
 * Schema for UpToPeriodsTypeEnum
 */
export const upToPeriodsTypeEnumSchema: Schema<UpToPeriodsTypeEnum> = stringEnum(
  UpToPeriodsTypeEnum
);
